name: Publish Extension

on:
  push:
    branches:
      - main
    paths:
      - 'package.json' # Only triggers when you bump the version!

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win32-x64
          - os: ubuntu-latest
            target: linux-x64
          - os: macos-latest
            target: darwin-x64
          - os: macos-latest
            target: darwin-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compile Extension
        run: npm run compile

      - name: Publish to Open VSX
        run: npx ovsx publish --target ${{ matrix.target }} -p ${{ secrets.OVSX_PAT }}

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish --target ${{ matrix.target }} -p ${{ secrets.VSCE_PAT }}
